### ISSUE TITLE
Create CSS colour palette for pomodoro tiles

### ISSUE THREAD

**Issue by clockworkpc** [clockworkpc/pomodoro-wall#17]
**app/views/pomodoro_cycles/show.html.erb**

```css
<style>
  .matrix {
    column-count: 10;
  }

  .blue {
    background-color: blue;
  }

  .green {
    background-color: green;
  }

  table, th, td {
    border: 1px solid black;
    column-count: 10;
  }

  body {
    margin: 0;
  }

  .container {
    width: auto;
    display: flex;
    flex-flow: row wrap;
    background: yellow;
    justify-content: flex-start;
    align-items: center;
    line-height: width / 10;
  }

  .box {
    background: red;
    color: white;
    font-size: 60px;
    text-align: center;
    line-height: 200px;

    width: 200px;
    height: 200px;
    margin: auto;
  }

  .green-box {
    background: green;
    color: white;
    font-size: 1.5em;
    text-align: center;
    margin: auto 1%;
    flex: 0 1 calc(8%);
    height: 100%;
    display: block;
  }

  .blue-box {
    background: blue;
    color: white;
    font-size: 1.5em;
    text-align: center;
    margin: auto 1%;
    flex: 0 1 calc(8%);
    height: 100%;
    display: block;
  }

</style>
```
